export { default as image_earphones_yx1 } from './image-earphones-yx1.jpg'
export { default as image_hero } from './image-hero.jpg'
export { default as image_speaker_zx7 } from './image-speaker-zx7.jpg'
export { default as image_speaker_zx9 } from './image-speaker-zx9.png'
export { default as image_headset } from './image-headset.png'
